import os

output_dir = "/Users/toanle/Documents/DEV/MyDocuments/SS English/phase-7/skill-7-behind-the-wheel"
os.makedirs(output_dir, exist_ok=True)

vocab_list = [
    {
        "filename": "Van.md",
        "word": "Van",
        "pos": "Noun",
        "ipa": "/væn/",
        "meaning": "Xe tải nhỏ, xe bán tải.",
        "v1_en": "A small vehicle used for carrying goods or people.",
        "v1_ipa": "/ə smɔːl ˈviːɪkəl juːzd fɔːr ˈkæriɪŋ ɡʊdz ɔːr ˈpiːpəl/",
        "v1_vi": "Một loại xe nhỏ được dùng để chở hàng hoặc chở người.",
        "v2_en": "A covered commercial vehicle used to transport goods or groups of passengers.",
        "v2_ipa": "/ə ˈkʌvərd kəˈmɜːrʃəl ˈviːɪkəl juːzd tu trænˈspɔːrt ɡʊdz ɔːr ɡruːps ʌv ˈpæsɪndʒərz/",
        "v2_vi": "Một phương tiện thương mại có mái che dùng để vận chuyển hàng hóa hoặc các nhóm hành khách.",
        "v3_en": "The delivery man drove a white van to drop off our packages.",
        "v3_ipa": "/ðə dɪˈlɪvəri mæn droʊv ə waɪt væn tu drɑːp ɔːf ˈaʊər ˈpækɪdʒɪz/",
        "v3_vi": "Người giao hàng đã lái chiếc xe tải nhỏ màu trắng để giao các gói hàng của chúng tôi."
    },
    {
        "filename": "Helicopter.md",
        "word": "Helicopter",
        "pos": "Noun",
        "ipa": "/ˈhɛlɪkɑːptər/",
        "meaning": "Trực thăng.",
        "v1_en": "A flying vehicle with large spinning blades on top.",
        "v1_ipa": "/ə ˈflaɪɪŋ ˈviːɪkəl wɪθ lɑːrdʒ ˈspɪnɪŋ bleɪdz ɑːn tɑːp/",
        "v1_vi": "Một phương tiện bay với những cánh quạt lớn quay trên nóc.",
        "v2_en": "An aircraft that derives its lift from blades that rotate about an approximately vertical central axis.",
        "v2_ipa": "/ən ˈɛrkræft ðæt dɪˈraɪvz ɪts lɪft frəm bleɪdz ðæt ˈroʊteɪt əˈbaʊt ən əˈprɑːksɪmətli ˈvɜːrtɪkəl ˈsɛntrəl ˈæksɪs/",
        "v2_vi": "Một loại máy bay có được lực nâng từ các cánh quạt quay quanh một trục trung tâm gần như thẳng đứng.",
        "v3_en": "The rescue team used a helicopter to reach the injured hikers on the mountain.",
        "v3_ipa": "/ðə ˈrɛskjuː tiːm juːzd ə ˈhɛlɪkɑːptər tu riːtʃ ðə ˈɪndʒərd ˈhaɪkərz ɑːn ðə ˈmaʊntən/",
        "v3_vi": "Đội cứu hộ đã sử dụng trực thăng để tiếp cận những người đi bộ leo núi bị thương trên ngọn núi."
    },
    {
        "filename": "Subway Train.md",
        "word": "Subway Train",
        "pos": "Noun",
        "ipa": "/ˈsʌbweɪ treɪn/",
        "meaning": "Tàu điện ngầm.",
        "v1_en": "A train that travels in tunnels under a city.",
        "v1_ipa": "/ə treɪn ðæt ˈtrævəlz ɪn ˈtʌnəlz ˈʌndər ə ˈsɪti/",
        "v1_vi": "Một loại tàu chạy trong các đường hầm dưới lòng thành phố.",
        "v2_en": "An electric passenger railway operating in an underground tunnel system.",
        "v2_ipa": "/ən ɪˈlɛktrɪk ˈpæsɪndʒər ˈreɪlweɪ ˈɑːpəreɪtɪŋ ɪn ən ˈʌndərɡraʊnd ˈtʌnəl ˈsɪstəm/",
        "v2_vi": "Một hệ thống đường sắt chở khách chạy bằng điện hoạt động trong hệ thống đường hầm ngầm.",
        "v3_en": "I take the subway train to work every morning to avoid traffic jams.",
        "v3_ipa": "/aɪ teɪk ðə ˈsʌbweɪ treɪn tu wɜːrk ˈɛvri ˈmɔːrnɪŋ tu əˈvɔɪd ˈtræfɪk dʒæmz/",
        "v3_vi": "Tôi đi tàu điện ngầm đi làm mỗi sáng để tránh kẹt xe."
    },
    {
        "filename": "Train.md",
        "word": "Train",
        "pos": "Noun",
        "ipa": "/treɪn/",
        "meaning": "Tàu hỏa, xe lửa.",
        "v1_en": "A line of connected cars that travel along tracks.",
        "v1_ipa": "/ə laɪn ʌv kəˈnɛktɪd kɑːrz ðæt ˈtrævəl əˈlɔːŋ træks/",
        "v1_vi": "Một hàng các toa xe nối liền nhau di chuyển dọc theo đường ray.",
        "v2_en": "A series of connected railway vehicles powered by a locomotive, transporting passengers or freight.",
        "v2_ipa": "/ə ˈsɪriz ʌv kəˈnɛktɪd ˈreɪlweɪ ˈviːɪkəlz ˈpaʊərd baɪ ə ˌloʊkəˈmoʊtɪv, trænˈspɔːrtɪŋ ˈpæsɪndʒərz ɔːr freɪt/",
        "v2_vi": "Một loạt các phương tiện đường sắt kết nối với nhau được kéo bởi đầu máy, vận chuyển hành khách hoặc hàng hóa.",
        "v3_en": "We bought tickets to ride the express train to the next city.",
        "v3_ipa": "/wi bɔːt ˈtɪkɪts tu raɪd ðə ɪkˈsprɛs treɪn tu ðə nɛkst ˈsɪti/",
        "v3_vi": "Chúng tôi đã mua vé để đi tàu tốc hành đến thành phố tiếp theo."
    },
    {
        "filename": "Boat.md",
        "word": "Boat",
        "pos": "Noun",
        "ipa": "/boʊt/",
        "meaning": "Thuyền, tàu nhỏ.",
        "v1_en": "A small vehicle for traveling on water.",
        "v1_ipa": "/ə smɔːl ˈviːɪkəl fɔːr ˈtrævəlɪŋ ɑːn ˈwɔːtər/",
        "v1_vi": "Một phương tiện nhỏ để di chuyển trên mặt nước.",
        "v2_en": "A watercraft of varied sizes designed to float, plane, or travel across water.",
        "v2_ipa": "/ə ˈwɔːtərkræft ʌv ˈvɛrid ˈsaɪzɪz dɪˈzaɪnd tu floʊt, pleɪn, ɔːr ˈtrævəl əˈkrɔːs ˈwɔːtər/",
        "v2_vi": "Một phương tiện thủy có nhiều kích cỡ khác nhau được thiết kế để nổi, lướt hoặc di chuyển trên mặt nước.",
        "v3_en": "They rented a wooden boat to go fishing on the lake.",
        "v3_ipa": "/ðeɪ ˈrɛntɪd ə ˈwʊdən boʊt tu ɡoʊ ˈfɪʃɪŋ ɑːn ðə leɪk/",
        "v3_vi": "Họ đã thuê một chiếc thuyền gỗ để đi câu cá trên hồ."
    },
    {
        "filename": "Canoe.md",
        "word": "Canoe",
        "pos": "Noun",
        "ipa": "/kəˈnuː/",
        "meaning": "Thuyền ca-nô, xuồng (thường chèo bằng tay).",
        "v1_en": "A light, narrow boat that you move with a paddle.",
        "v1_ipa": "/ə laɪt, ˈnæroʊ boʊt ðæt ju muːv wɪθ ə ˈpædəl/",
        "v1_vi": "Một chiếc thuyền nhỏ, nhẹ, hẹp mà bạn di chuyển bằng mái chèo.",
        "v2_en": "A slender, open boat tapering to a point at both ends, propelled by paddling.",
        "v2_ipa": "/ə ˈslɛndər, ˈoʊpən boʊt ˈteɪpərɪŋ tu ə pɔɪnt æt boʊθ ɛndz, prəˈpɛld baɪ ˈpædlɪŋ/",
        "v2_vi": "Một chiếc thuyền nhỏ, hẹp, mở và thuôn nhọn ở cả hai đầu, được đẩy đi bằng cách chèo.",
        "v3_en": "We took the canoe down the river to enjoy the peaceful scenery.",
        "v3_ipa": "/wi tʊk ðə kəˈnuː daʊn ðə ˈrɪvər tu ɪnˈdʒɔɪ ðə ˈpiːsfəl ˈsiːnəri/",
        "v3_vi": "Chúng tôi đã chèo xuồng xuôi dòng sông để tận hưởng phong cảnh yên bình."
    },
    {
        "filename": "Truck.md",
        "word": "Truck",
        "pos": "Noun",
        "ipa": "/trʌk/",
        "meaning": "Xe tải.",
        "v1_en": "A large road vehicle used for carrying heavy things.",
        "v1_ipa": "/ə lɑːrdʒ roʊd ˈviːɪkəl juːzd fɔːr ˈkæriɪŋ ˈhɛvi θɪŋz/",
        "v1_vi": "Một loại phương tiện đường bộ lớn được dùng để chở những đồ vật nặng.",
        "v2_en": "A heavy motor vehicle designed primarily to transport cargo or massive payloads.",
        "v2_ipa": "/ə ˈhɛvi ˈmoʊtər ˈviːɪkəl dɪˈzaɪnd praɪˈmɛrəli tu trænˈspɔːrt ˈkɑːrɡoʊ ɔːr ˈmæsɪv ˈpeɪloʊdz/",
        "v2_vi": "Một phương tiện cơ giới hạng nặng được thiết kế chủ yếu để vận chuyển hàng hóa hoặc tải trọng lớn.",
        "v3_en": "The delivery truck parked right outside our house to drop off the new fridge.",
        "v3_ipa": "/ðə dɪˈlɪvəri trʌk pɑːrkt raɪt aʊtˈsaɪd ˈaʊər haʊs tu drɑːp ɔːf ðə nuː frɪdʒ/",
        "v3_vi": "Chiếc xe tải giao hàng đã đậu ngay bên ngoài nhà chúng tôi để giao chiếc tủ lạnh mới."
    },
    {
        "filename": "Submarine.md",
        "word": "Submarine",
        "pos": "Noun",
        "ipa": "/ˈsʌbməriːn/",
        "meaning": "Tàu ngầm.",
        "v1_en": "A ship that can travel completely underwater.",
        "v1_ipa": "/ə ʃɪp ðæt kæn ˈtrævəl kəmˈpliːtli ˌʌndərˈwɔːtər/",
        "v1_vi": "Một loại tàu có thể di chuyển hoàn toàn dưới nước.",
        "v2_en": "A specialized watercraft capable of independent operation beneath the surface of the water.",
        "v2_ipa": "/ə ˈspɛʃəlaɪzd ˈwɔːtərkræft ˈkeɪpəbəl ʌv ˌɪndɪˈpɛndənt ˌɑːpəˈreɪʃən bɪˈniːθ ðə ˈsɜːrfɪs ʌv ðə ˈwɔːtər/",
        "v2_vi": "Một loại phương tiện thủy chuyên dụng có khả năng hoạt động độc lập dưới mặt nước.",
        "v3_en": "The navy uses submarines to patrol the ocean depths silently.",
        "v3_ipa": "/ðə ˈneɪvi ˈjuːzɪz ˈsʌbməriːnz tu pəˈtroʊl ðə ˈoʊʃən dɛpθs ˈsaɪləntli/",
        "v3_vi": "Hải quân sử dụng tàu ngầm để tuần tra dưới độ sâu của đại dương một cách thầm lặng."
    },
    {
        "filename": "Car.md",
        "word": "Car",
        "pos": "Noun",
        "ipa": "/kɑːr/",
        "meaning": "Xe hơi, xe ô tô.",
        "v1_en": "A vehicle with four wheels that people drive on roads.",
        "v1_ipa": "/ə ˈviːɪkəl wɪθ fɔːr wiːlz ðæt ˈpiːpəl draɪv ɑːn roʊdz/",
        "v1_vi": "Một phương tiện có bốn bánh mà người ta lái trên đường.",
        "v2_en": "A four-wheeled motor vehicle used for transporting passengers.",
        "v2_ipa": "/ə fɔːr-wiːld ˈmoʊtər ˈviːɪkəl juːzd fɔːr trænˈspɔːrtɪŋ ˈpæsɪndʒərz/",
        "v2_vi": "Một phương tiện cơ giới có bốn bánh được sử dụng để chở hành khách.",
        "v3_en": "She bought a new electric car to save money on gas.",
        "v3_ipa": "/ʃi bɔːt ə nuː ɪˈlɛktrɪk kɑːr tu seɪv ˈmʌni ɑːn ɡæs/",
        "v3_vi": "Cô ấy đã mua một chiếc xe hơi điện mới để tiết kiệm tiền đổ xăng."
    },
    {
        "filename": "Luggage Trolley.md",
        "word": "Luggage Trolley",
        "pos": "Noun",
        "ipa": "/ˈlʌɡɪdʒ ˈtrɑːli/",
        "meaning": "Xe đẩy hành lý.",
        "v1_en": "A small cart you use at the airport to push your bags.",
        "v1_ipa": "/ə smɔːl kɑːrt ju juːz æt ðə ˈɛrpɔːrt tu pʊʃ jʊər bæɡz/",
        "v1_vi": "Một chiếc xe đẩy nhỏ mà bạn dùng ở sân bay để đẩy hành lý.",
        "v2_en": "A wheeled cart utilized by travelers to easily transport heavy luggage in transport hubs.",
        "v2_ipa": "/ə wiːld kɑːrt ˈjuːtəlaɪzd baɪ ˈtrævələrz tu ˈiːzɪli trænˈspɔːrt ˈhɛvi ˈlʌɡɪdʒ ɪn trænˈspɔːrt hʌbz/",
        "v2_vi": "Một loại xe đẩy có bánh được hành khách sử dụng để dễ dàng vận chuyển hành lý nặng tại các nhà ga/sân bay.",
        "v3_en": "I loaded all three of my heavy suitcases onto the luggage trolley.",
        "v3_ipa": "/aɪ ˈloʊdɪd ɔːl θriː ʌv maɪ ˈhɛvi ˈsuːtkeɪsɪz ˈɑːntu ðə ˈlʌɡɪdʒ ˈtrɑːli/",
        "v3_vi": "Tôi đã chất cả ba chiếc vali nặng nề của mình lên xe đẩy hành lý."
    },
    {
        "filename": "Motorboat.md",
        "word": "Motorboat",
        "pos": "Noun",
        "ipa": "/ˈmoʊtərboʊt/",
        "meaning": "Thuyền máy, xuồng máy.",
        "v1_en": "A boat that moves fast using an engine.",
        "v1_ipa": "/ə boʊt ðæt muːvz fæst ˈjuːzɪŋ ən ˈɛndʒɪn/",
        "v1_vi": "Một chiếc thuyền di chuyển nhanh bằng động cơ.",
        "v2_en": "A watercraft powered by an inboard or outboard internal combustion engine.",
        "v2_ipa": "/ə ˈwɔːtərkræft ˈpaʊərd baɪ ən ˈɪnbɔːrd ɔːr ˈaʊtbɔːrd ɪnˈtɜːrnəl kəmˈbʌstʃən ˈɛndʒɪn/",
        "v2_vi": "Một phương tiện thủy chạy bằng động cơ đốt trong gắn trong hoặc ngoài tàu.",
        "v3_en": "We rode a motorboat across the bay to reach the island quickly.",
        "v3_ipa": "/wi roʊd ə ˈmoʊtərboʊt əˈkrɔːs ðə beɪ tu riːtʃ ðə ˈaɪlənd ˈkwɪkli/",
        "v3_vi": "Chúng tôi đã đi thuyền máy băng qua vịnh để ra đảo thật nhanh."
    },
    {
        "filename": "Caravan.md",
        "word": "Caravan",
        "pos": "Noun",
        "ipa": "/ˈkærəvæn/",
        "meaning": "Xe nhà di động, đoàn xe (người Anh hay dùng để chỉ xe kéo du lịch).",
        "v1_en": "A vehicle you can pull with a car and sleep in when you travel.",
        "v1_ipa": "/ə ˈviːɪkəl ju kæn pʊl wɪθ ə kɑːr ænd sliːp ɪn wɛn ju ˈtrævəl/",
        "v1_vi": "Một loại xe bạn có thể kéo theo bằng ô tô và ngủ trong đó khi đi du lịch.",
        "v2_en": "A mobile home or trailer designed to be towed behind a vehicle for recreational camping.",
        "v2_ipa": "/ə ˈmoʊbəl hoʊm ɔːr ˈtreɪlər dɪˈzaɪnd tu bi toʊd bɪˈhaɪnd ə ˈviːɪkəl fɔːr ˌrɛkriˈeɪʃənəl ˈkæmpɪŋ/",
        "v2_vi": "Một ngôi nhà di động hoặc xe kéo được thiết kế để kéo phía sau một phương tiện dùng cho việc cắm trại dã ngoại.",
        "v3_en": "Our family stayed in a caravan near the beach during the summer holiday.",
        "v3_ipa": "/ˈaʊər ˈfæməli steɪd ɪn ə ˈkærəvæn nɪr ðə biːtʃ ˈdʊrɪŋ ðə ˈsʌmər ˈhɑːlədeɪ/",
        "v3_vi": "Gia đình chúng tôi đã ở trong một chiếc xe nhà di động gần bãi biển trong kỳ nghỉ hè."
    },
    {
        "filename": "Lorry.md",
        "word": "Lorry",
        "pos": "Noun",
        "ipa": "/ˈlɔːri/",
        "meaning": "Xe tải (Tiếng Anh-Anh).",
        "v1_en": "A large truck used for transporting heavy goods.",
        "v1_ipa": "/ə lɑːrdʒ trʌk juːzd fɔːr trænˈspɔːrtɪŋ ˈhɛvi ɡʊdz/",
        "v1_vi": "Một chiếc xe tải lớn dùng để vận chuyển những hàng hóa nặng.",
        "v2_en": "A heavy motor vehicle designed for carrying loads, predominantly a British term for a truck.",
        "v2_ipa": "/ə ˈhɛvi ˈmoʊtər ˈviːɪkəl dɪˈzaɪnd fɔːr ˈkæriɪŋ loʊdz, prɪˈdɑːmɪnəntli ə ˈbrɪtɪʃ tɜːrm fɔːr ə trʌk/",
        "v2_vi": "Một phương tiện cơ giới hạng nặng được thiết kế để chở hàng, chủ yếu là thuật ngữ Anh-Anh dùng cho từ 'xe tải'.",
        "v3_en": "The lorry was carrying tons of building materials to the construction site.",
        "v3_ipa": "/ðə ˈlɔːri wəz ˈkæriɪŋ tʌnz ʌv ˈbɪldɪŋ məˈtɪriəlz tu ðə kənˈstrʌkʃən saɪt/",
        "v3_vi": "Chiếc xe tải lớn đang chở hàng tấn vật liệu xây dựng đến công trường."
    },
    {
        "filename": "Ferry.md",
        "word": "Ferry",
        "pos": "Noun",
        "ipa": "/ˈfɛri/",
        "meaning": "Phà, bến phà.",
        "v1_en": "A boat that carries people or cars across a river or sea.",
        "v1_ipa": "/ə boʊt ðæt ˈkæriz ˈpiːpəl ɔːr kɑːrz əˈkrɔːs ə ˈrɪvər ɔːr siː/",
        "v1_vi": "Một loại tàu chở người hoặc xe cộ qua sông hoặc biển.",
        "v2_en": "A vessel specifically designed for the regular transport of passengers, vehicles, or goods across a body of water.",
        "v2_ipa": "/ə ˈvɛsəl spəˈsɪfɪkli dɪˈzaɪnd fɔːr ðə ˈrɛɡjələr trænˈspɔːrt ʌv ˈpæsɪndʒərz, ˈviːɪkəlz, ɔːr ɡʊdz əˈkrɔːs ə ˈbɑːdi ʌv ˈwɔːtər/",
        "v2_vi": "Một tàu thuyền được thiết kế đặc biệt để vận chuyển hành khách, xe cộ hoặc hàng hóa thường xuyên qua một vùng nước.",
        "v3_en": "We drove our car onto the ferry to cross over to the island.",
        "v3_ipa": "/wi droʊv ˈaʊər kɑːr ˈɑːntu ðə ˈfɛri tu krɔːs ˈoʊvər tu ðə ˈaɪlənd/",
        "v3_vi": "Chúng tôi đã lái ô tô của mình lên phà để băng qua đảo."
    },
    {
        "filename": "Police Car.md",
        "word": "Police Car",
        "pos": "Noun",
        "ipa": "/pəˈliːs kɑːr/",
        "meaning": "Xe cảnh sát.",
        "v1_en": "A car driven by police officers, usually with flashing lights and a siren.",
        "v1_ipa": "/ə kɑːr ˈdrɪvən baɪ pəˈliːs ˈɔːfɪsərz, ˈjuːʒuəli wɪθ ˈflæʃɪŋ laɪts ænd ə ˈsaɪrən/",
        "v1_vi": "Một chiếc xe được điều khiển bởi cảnh sát, thường có đèn nháy và còi hú.",
        "v2_en": "A specially modified vehicle used by law enforcement personnel for patrol and emergency response.",
        "v2_ipa": "/ə ˈspɛʃəli ˈmɑːdəfaɪd ˈviːɪkəl juːzd baɪ lɔː ɪnˈfɔːrsmənt ˌpɜːrsəˈnɛl fɔːr pəˈtroʊl ænd ɪˈmɜːrdʒənsi rɪˈspɑːns/",
        "v2_vi": "Một phương tiện được điều chỉnh đặc biệt được lực lượng thực thi pháp luật sử dụng để tuần tra và phản ứng khẩn cấp.",
        "v3_en": "A police car rushed down the street with its siren blaring.",
        "v3_ipa": "/ə pəˈliːs kɑːr rʌʃt daʊn ðə striːt wɪθ ɪts ˈsaɪrən ˈblɛrɪŋ/",
        "v3_vi": "Một chiếc xe cảnh sát lao nhanh xuống phố với tiếng còi inh ỏi."
    },
    {
        "filename": "Double-decker Bus.md",
        "word": "Double-decker Bus",
        "pos": "Noun",
        "ipa": "/ˌdʌbəlˈdɛkər bʌs/",
        "meaning": "Xe buýt hai tầng.",
        "v1_en": "A tall bus that has two levels for passengers to sit on.",
        "v1_ipa": "/ə tɔːl bʌs ðæt hæz tuː ˈlɛvəlz fɔːr ˈpæsɪndʒərz tu sɪt ɑːn/",
        "v1_vi": "Một chiếc xe buýt cao có hai tầng cho hành khách ngồi.",
        "v2_en": "A public transport vehicle with an upper and lower seating deck, commonly found in cities like London.",
        "v2_ipa": "/ə ˈpʌblɪk ˈtrænspɔːrt ˈviːɪkəl wɪθ ən ˈʌpər ænd ˈloʊər ˈsiːtɪŋ dɛk, ˈkɑːmənli faʊnd ɪn ˈsɪtiz laɪk ˈlʌndən/",
        "v2_vi": "Một phương tiện giao thông công cộng có tầng ghế ngồi phía trên và phía dưới, thường thấy ở các thành phố như London.",
        "v3_en": "Tourists love sitting on the top level of the double-decker bus to see the whole city.",
        "v3_ipa": "/ˈtʊrɪsts lʌv ˈsɪtɪŋ ɑːn ðə tɑːp ˈlɛvəl ʌv ðə ˌdʌbəlˈdɛkər bʌs tu siː ðə hoʊl ˈsɪti/",
        "v3_vi": "Du khách rất thích ngồi trên tầng cao nhất của xe buýt hai tầng để ngắm nhìn toàn cảnh thành phố."
    },
    {
        "filename": "Skateboard.md",
        "word": "Skateboard",
        "pos": "Noun",
        "ipa": "/ˈskeɪtbɔːrd/",
        "meaning": "Ván trượt.",
        "v1_en": "A short board with four wheels that you stand on and ride.",
        "v1_ipa": "/ə ʃɔːrt bɔːrd wɪθ fɔːr wiːlz ðæt ju stænd ɑːn ænd raɪd/",
        "v1_vi": "Một tấm ván ngắn có bốn bánh mà bạn đứng lên và trượt.",
        "v2_en": "A piece of sporting equipment consisting of a small flat board mounted on four small wheels.",
        "v2_ipa": "/ə piːs ʌv ˈspɔːrtɪŋ ɪˈkwɪpmənt kənˈsɪstɪŋ ʌv ə smɔːl flæt bɔːrd ˈmaʊntɪd ɑːn fɔːr smɔːl wiːlz/",
        "v2_vi": "Một dụng cụ thể thao bao gồm một tấm ván phẳng nhỏ được gắn trên bốn bánh xe nhỏ.",
        "v3_en": "The teenager was doing tricks on his skateboard at the park.",
        "v3_ipa": "/ðə ˈtiːneɪdʒər wəz ˈduːɪŋ trɪks ɑːn hɪz ˈskeɪtbɔːrd æt ðə pɑːrk/",
        "v3_vi": "Cậu thiếu niên đang thực hiện các kỹ xảo trên chiếc ván trượt của mình tại công viên."
    },
    {
        "filename": "Air Plane.md",
        "word": "Air Plane",
        "pos": "Noun",
        "ipa": "/ˈɛrpleɪn/",
        "meaning": "Máy bay.",
        "v1_en": "A flying vehicle with wings and engines that carries passengers.",
        "v1_ipa": "/ə ˈflaɪɪŋ ˈviːɪkəl wɪθ wɪŋz ænd ˈɛndʒɪnz ðæt ˈkæriz ˈpæsɪndʒərz/",
        "v1_vi": "Một phương tiện bay có cánh và động cơ dùng để chở hành khách.",
        "v2_en": "A fixed-wing aircraft powered by jet engines or propellers, designed for high-speed air travel.",
        "v2_ipa": "/ə fɪkst-wɪŋ ˈɛrkræft ˈpaʊərd baɪ dʒɛt ˈɛndʒɪnz ɔːr prəˈpɛlərz, dɪˈzaɪnd fɔːr haɪ-spiːd ɛr ˈtrævəl/",
        "v2_vi": "Máy bay cánh cố định chạy bằng động cơ phản lực hoặc cánh quạt, được thiết kế để di chuyển trên không với tốc độ cao.",
        "v3_en": "We boarded the air plane right before it took off for New York.",
        "v3_ipa": "/wi ˈbɔːrdɪd ðə ˈɛrpleɪn raɪt bɪˈfɔːr ɪt tʊk ɔːf fɔːr nuː jɔːrk/",
        "v3_vi": "Chúng tôi đã lên máy bay ngay trước khi nó cất cánh đến New York."
    },
    {
        "filename": "Mountain Bike.md",
        "word": "Mountain Bike",
        "pos": "Noun",
        "ipa": "/ˈmaʊntən baɪk/",
        "meaning": "Xe đạp leo núi, xe đạp địa hình.",
        "v1_en": "A bicycle made for riding on rough, rocky, and dirt trails.",
        "v1_ipa": "/ə ˈbaɪsɪkəl meɪd fɔːr ˈraɪdɪŋ ɑːn rʌf, ˈrɑːki, ænd dɜːrt treɪlz/",
        "v1_vi": "Một loại xe đạp được chế tạo để chạy trên những con đường mòn gồ ghề, nhiều đá và đất.",
        "v2_en": "A robustly constructed bicycle designed specifically for off-road cycling over uneven terrain.",
        "v2_ipa": "/ə roʊˈbʌstli kənˈstrʌktɪd ˈbaɪsɪkəl dɪˈzaɪnd spəˈsɪfɪkli fɔːr ɔːf-roʊd ˈsaɪklɪŋ ˈoʊvər ʌnˈiːvən tɛˈreɪn/",
        "v2_vi": "Một chiếc xe đạp có kết cấu chắc chắn được thiết kế dành riêng cho việc đạp xe địa hình trên các địa hình gập ghềnh.",
        "v3_en": "He rides his mountain bike through the forest trails every weekend.",
        "v3_ipa": "/hi raɪdz hɪz ˈmaʊntən baɪk θruː ðə ˈfɔːrɪst treɪlz ˈɛvri ˈwiːkɛnd/",
        "v3_vi": "Anh ấy lái xe đạp địa hình băng qua những con đường mòn trong rừng vào mỗi cuối tuần."
    },
    {
        "filename": "Ambulance.md",
        "word": "Ambulance",
        "pos": "Noun",
        "ipa": "/ˈæmbjələns/",
        "meaning": "Xe cứu thương.",
        "v1_en": "A special vehicle that takes sick or hurt people to the hospital.",
        "v1_ipa": "/ə ˈspɛʃəl ˈviːɪkəl ðæt teɪks sɪk ɔːr hɜːrt ˈpiːpəl tu ðə ˈhɑːspɪtəl/",
        "v1_vi": "Một phương tiện đặc biệt chuyên chở những người bệnh hoặc bị thương đến bệnh viện.",
        "v2_en": "A medically equipped vehicle designed to transport patients in critical condition to medical facilities.",
        "v2_ipa": "/ə ˈmɛdɪkli ɪˈkwɪpt ˈviːɪkəl dɪˈzaɪnd tu trænˈspɔːrt ˈpeɪʃənts ɪn ˈkrɪtɪkəl kənˈdɪʃən tu ˈmɛdɪkəl fəˈsɪlɪtiz/",
        "v2_vi": "Một phương tiện được trang bị y tế được thiết kế để vận chuyển bệnh nhân trong tình trạng nguy kịch đến các cơ sở y tế.",
        "v3_en": "They called an ambulance immediately when the man collapsed on the street.",
        "v3_ipa": "/ðeɪ kɔːld ən ˈæmbjələns ɪˈmiːdiətli wɛn ðə mæn kəˈlæpst ɑːn ðə striːt/",
        "v3_vi": "Họ đã gọi xe cứu thương ngay lập tức khi người đàn ông gục xuống trên đường."
    },
    {
        "filename": "Carriage.md",
        "word": "Carriage",
        "pos": "Noun",
        "ipa": "/ˈkærɪdʒ/",
        "meaning": "Cỗ xe ngựa, toa hành khách (tàu hỏa).",
        "v1_en": "A vehicle with wheels pulled by horses, or a part of a train.",
        "v1_ipa": "/ə ˈviːɪkəl wɪθ wiːlz pʊld baɪ ˈhɔːrsɪz, ɔːr ə pɑːrt ʌv ə treɪn/",
        "v1_vi": "Một phương tiện có bánh xe do ngựa kéo, hoặc một phần của đoàn tàu.",
        "v2_en": "A four-wheeled passenger vehicle traditionally drawn by horses, or a railway passenger coach.",
        "v2_ipa": "/ə fɔːr-wiːld ˈpæsɪndʒər ˈviːɪkəl trəˈdɪʃənəli drɔːn baɪ ˈhɔːrsɪz, ɔːr ə ˈreɪlweɪ ˈpæsɪndʒər koʊtʃ/",
        "v2_vi": "Một phương tiện chở khách có bốn bánh truyền thống do ngựa kéo, hoặc một toa hành khách của đường sắt.",
        "v3_en": "They took a romantic ride in a horse-drawn carriage through the park.",
        "v3_ipa": "/ðeɪ tʊk ə roʊˈmæntɪk raɪd ɪn ə hɔːrs-drɔːn ˈkærɪdʒ θruː ðə pɑːrk/",
        "v3_vi": "Họ đã có một chuyến đi lãng mạn trên cỗ xe ngựa dạo qua công viên."
    },
    {
        "filename": "Pedicab.md",
        "word": "Pedicab",
        "pos": "Noun",
        "ipa": "/ˈpɛdɪkæb/",
        "meaning": "Xe xích lô, xe đạp lôi.",
        "v1_en": "A bicycle with three wheels that carries passengers in the back.",
        "v1_ipa": "/ə ˈbaɪsɪkəl wɪθ θriː wiːlz ðæt ˈkæriz ˈpæsɪndʒərz ɪn ðə bæk/",
        "v1_vi": "Một chiếc xe đạp ba bánh chuyên chở hành khách ở phía sau.",
        "v2_en": "A small cycle rickshaw propelled by pedaling, utilized as a taxi for short urban trips.",
        "v2_ipa": "/ə smɔːl ˈsaɪkəl ˈrɪkʃɔː prəˈpɛld baɪ ˈpɛdəlɪŋ, ˈjuːtəlaɪzd æz ə ˈtæksi fɔːr ʃɔːrt ˈɜːrbən trɪps/",
        "v2_vi": "Một chiếc xe kéo chạy bằng sức đạp, được sử dụng làm phương tiện taxi cho các chuyến đi ngắn trong đô thị.",
        "v3_en": "We hired a pedicab to take a slow tour around the old city streets.",
        "v3_ipa": "/wi ˈhaɪərd ə ˈpɛdɪkæb tu teɪk ə sloʊ tʊr əˈraʊnd ðə oʊld ˈsɪti striːts/",
        "v3_vi": "Chúng tôi đã thuê một chiếc xích lô để đi một vòng chậm rãi ngắm cảnh quanh các khu phố cổ."
    },
    {
        "filename": "Garbage Truck.md",
        "word": "Garbage Truck",
        "pos": "Noun",
        "ipa": "/ˈɡɑːrbɪdʒ trʌk/",
        "meaning": "Xe chở rác.",
        "v1_en": "A large truck that picks up and takes away trash.",
        "v1_ipa": "/ə lɑːrdʒ trʌk ðæt pɪks ʌp ænd teɪks əˈweɪ træʃ/",
        "v1_vi": "Một chiếc xe tải lớn chuyên thu gom và chở rác đi.",
        "v2_en": "A specialized heavy-duty vehicle designed to collect and transport municipal solid waste.",
        "v2_ipa": "/ə ˈspɛʃəlaɪzd ˈhɛvi-ˈduːti ˈviːɪkəl dɪˈzaɪnd tu kəˈlɛkt ænd trænˈspɔːrt mjuːˈnɪsɪpəl ˈsɑːlɪd weɪst/",
        "v2_vi": "Một loại phương tiện chuyên dụng tải trọng nặng được thiết kế để thu gom và vận chuyển chất thải rắn đô thị.",
        "v3_en": "The garbage truck comes to our neighborhood every Tuesday morning.",
        "v3_ipa": "/ðə ˈɡɑːrbɪdʒ trʌk kʌmz tu ˈaʊər ˈneɪbərhʊd ˈɛvri ˈtuːzdeɪ ˈmɔːrnɪŋ/",
        "v3_vi": "Chiếc xe chở rác đến khu phố của chúng tôi vào mỗi sáng thứ Ba."
    },
    {
        "filename": "Ship.md",
        "word": "Ship",
        "pos": "Noun",
        "ipa": "/ʃɪp/",
        "meaning": "Tàu thủy, con tàu (lớn).",
        "v1_en": "A very large boat used for traveling across the ocean.",
        "v1_ipa": "/ə ˈvɛri lɑːrdʒ boʊt juːzd fɔːr ˈtrævəlɪŋ əˈkrɔːs ðə ˈoʊʃən/",
        "v1_vi": "Một chiếc thuyền rất lớn được dùng để đi ngang qua đại dương.",
        "v2_en": "A substantial seagoing vessel designed for long-distance transport of cargo or passengers.",
        "v2_ipa": "/ə səbˈstænʃəl ˈsiːɡoʊɪŋ ˈvɛsəl dɪˈzaɪnd fɔːr lɔːŋ-ˈdɪstəns trænˈspɔːrt ʌv ˈkɑːrɡoʊ ɔːr ˈpæsɪndʒərz/",
        "v2_vi": "Một con tàu biển lớn được thiết kế để vận chuyển hàng hóa hoặc hành khách đường dài.",
        "v3_en": "The massive cargo ship set sail across the Pacific Ocean.",
        "v3_ipa": "/ðə ˈmæsɪv ˈkɑːrɡoʊ ʃɪp sɛt seɪl əˈkrɔːs ðə pəˈsɪfɪk ˈoʊʃən/",
        "v3_vi": "Con tàu chở hàng khổng lồ đã giương buồm băng qua Thái Bình Dương."
    },
    {
        "filename": "Taxi.md",
        "word": "Taxi",
        "pos": "Noun",
        "ipa": "/ˈtæksi/",
        "meaning": "Xe tắc-xi.",
        "v1_en": "A car you pay to ride in, driven by a professional driver.",
        "v1_ipa": "/ə kɑːr ju peɪ tu raɪd ɪn, ˈdrɪvən baɪ ə prəˈfɛʃənəl ˈdraɪvər/",
        "v1_vi": "Một chiếc xe mà bạn trả tiền để đi, được lái bởi một tài xế chuyên nghiệp.",
        "v2_en": "A commercially licensed passenger vehicle available for hire with a driver.",
        "v2_ipa": "/ə kəˈmɜːrʃəli ˈlaɪsənst ˈpæsɪndʒər ˈviːɪkəl əˈveɪləbəl fɔːr haɪr wɪθ ə ˈdraɪvər/",
        "v2_vi": "Một phương tiện chở khách được cấp phép thương mại có sẵn để thuê cùng với một tài xế.",
        "v3_en": "I missed the bus, so I had to catch a taxi to get to work on time.",
        "v3_ipa": "/aɪ mɪst ðə bʌs, soʊ aɪ hæd tu kætʃ ə ˈtæksi tu ɡɛt tu wɜːrk ɑːn taɪm/",
        "v3_vi": "Tôi đã lỡ chuyến xe buýt, vì vậy tôi phải bắt taxi để đến chỗ làm đúng giờ."
    },
    {
        "filename": "Cab.md",
        "word": "Cab",
        "pos": "Noun",
        "ipa": "/kæb/",
        "meaning": "Xe taxi (cách gọi khác).",
        "v1_en": "Another word for a taxi.",
        "v1_ipa": "/əˈnʌðər wɜːrd fɔːr ə ˈtæksi/",
        "v1_vi": "Một từ khác để chỉ xe taxi.",
        "v2_en": "A colloquial term commonly used to refer to a taxi, especially in metropolitan areas.",
        "v2_ipa": "/ə kəˈloʊkwiəl tɜːrm ˈkɑːmənli juːzd tu rɪˈfɜːr tu ə ˈtæksi, ɪˈspɛʃəli ɪn ˌmɛtrəˈpɑːlɪtən ˈɛriəz/",
        "v2_vi": "Một thuật ngữ thông tục thường được dùng để chỉ xe taxi, đặc biệt là ở các khu vực đô thị.",
        "v3_en": "Let's hail a cab since it's starting to rain heavily.",
        "v3_ipa": "/lɛts heɪl ə kæb sɪns ɪts ˈstɑːrtɪŋ tu reɪn ˈhɛvɪli/",
        "v3_vi": "Hãy gọi một chiếc taxi vì trời bắt đầu mưa to rồi."
    },
    {
        "filename": "Kayak.md",
        "word": "Kayak",
        "pos": "Noun",
        "ipa": "/ˈkaɪæk/",
        "meaning": "Thuyền ca-dắc (thường cho một người với mái chèo hai mũi).",
        "v1_en": "A small, narrow boat for one person, moved by a paddle with two ends.",
        "v1_ipa": "/ə smɔːl, ˈnæroʊ boʊt fɔːr wʌn ˈpɜːrsən, muːvd baɪ ə ˈpædəl wɪθ tuː ɛndz/",
        "v1_vi": "Một chiếc thuyền nhỏ và hẹp dành cho một người, được di chuyển bằng một mái chèo có hai đầu.",
        "v2_en": "A sleek, low-to-the-water boat propelled by a double-bladed paddle, originating from indigenous Arctic peoples.",
        "v2_ipa": "/ə sliːk, loʊ-tu-ðə-ˈwɔːtər boʊt prəˈpɛld baɪ ə ˈdʌbəl-ˈbleɪdɪd ˈpædəl, əˈrɪdʒɪneɪtɪŋ frəm ɪnˈdɪdʒənəs ˈɑːrktɪk ˈpiːpəlz/",
        "v2_vi": "Một chiếc thuyền kiểu dáng thuôn dài sát mặt nước, được đẩy đi bằng mái chèo hai cánh, bắt nguồn từ các dân tộc bản địa ở Bắc Cực.",
        "v3_en": "He went down the rapid river in his single-seat kayak.",
        "v3_ipa": "/hi wɛnt daʊn ðə ˈræpɪd ˈrɪvər ɪn hɪz ˈsɪŋɡəl-siːt ˈkaɪæk/",
        "v3_vi": "Anh ấy đã chèo dọc theo dòng sông chảy xiết bằng chiếc thuyền ca-dắc một chỗ ngồi của mình."
    },
    {
        "filename": "Coach.md",
        "word": "Coach",
        "pos": "Noun",
        "ipa": "/koʊtʃ/",
        "meaning": "Xe khách (chạy đường dài).",
        "v1_en": "A large, comfortable bus used for traveling long distances.",
        "v1_ipa": "/ə lɑːrdʒ, ˈkʌmftərbəl bʌs juːzd fɔːr ˈtrævəlɪŋ lɔːŋ ˈdɪstənsɪz/",
        "v1_vi": "Một chiếc xe buýt lớn, thoải mái được dùng để đi du lịch đường dài.",
        "v2_en": "An intercity transport bus equipped with comfortable seating and amenities for extended journeys.",
        "v2_ipa": "/ən ˌɪntərˈsɪti ˈtrænspɔːrt bʌs ɪˈkwɪpt wɪθ ˈkʌmftərbəl ˈsiːtɪŋ ænd əˈmɛnɪtiz fɔːr ɪkˈstɛndɪd ˈdʒɜːrniz/",
        "v2_vi": "Xe buýt vận tải liên tỉnh được trang bị chỗ ngồi thoải mái và các tiện nghi cho những chuyến đi kéo dài.",
        "v3_en": "We booked a trip on a luxury coach to travel across the country.",
        "v3_ipa": "/wi bʊkt ə trɪp ɑːn ə ˈlʌkʃəri koʊtʃ tu ˈtrævəl əˈkrɔːs ðə ˈkʌntri/",
        "v3_vi": "Chúng tôi đã đặt một chuyến đi trên một chiếc xe khách sang trọng để du lịch xuyên quốc gia."
    },
    {
        "filename": "Baby Carriage.md",
        "word": "Baby Carriage",
        "pos": "Noun",
        "ipa": "/ˈbeɪbi ˈkærɪdʒ/",
        "meaning": "Xe nôi (cho trẻ sơ sinh).",
        "v1_en": "A small bed on wheels used to push a baby around.",
        "v1_ipa": "/ə smɔːl bɛd ɑːn wiːlz juːzd tu pʊʃ ə ˈbeɪbi əˈraʊnd/",
        "v1_vi": "Một chiếc giường nhỏ có bánh xe được dùng để đẩy em bé đi dạo.",
        "v2_en": "A four-wheeled conveyance for transporting an infant in a lying-down position.",
        "v2_ipa": "/ə fɔːr-wiːld kənˈveɪəns fɔːr trænˈspɔːrtɪŋ ən ˈɪnfənt ɪn ə ˈlaɪɪŋ-daʊn pəˈzɪʃən/",
        "v2_vi": "Một phương tiện bốn bánh dùng để vận chuyển một em bé ở tư thế nằm.",
        "v3_en": "The mother gently pushed the baby carriage through the park.",
        "v3_ipa": "/ðə ˈmʌðər ˈdʒɛntli pʊʃt ðə ˈbeɪbi ˈkærɪdʒ θruː ðə pɑːrk/",
        "v3_vi": "Người mẹ nhẹ nhàng đẩy chiếc xe nôi đi dạo quanh công viên."
    },
    {
        "filename": "Pram.md",
        "word": "Pram",
        "pos": "Noun",
        "ipa": "/præm/",
        "meaning": "Xe nôi (Tiếng Anh-Anh).",
        "v1_en": "A British word for a baby carriage.",
        "v1_ipa": "/ə ˈbrɪtɪʃ wɜːrd fɔːr ə ˈbeɪbi ˈkærɪdʒ/",
        "v1_vi": "Một từ tiếng Anh-Anh để chỉ xe đẩy cho em bé (xe nôi).",
        "v2_en": "A traditional term in British English for a perambulator, designed to carry a sleeping infant.",
        "v2_ipa": "/ə trəˈdɪʃənəl tɜːrm ɪn ˈbrɪtɪʃ ˈɪŋɡlɪʃ fɔːr ə pəˈræmbjʊleɪtər, dɪˈzaɪnd tu ˈkæri ə ˈsliːpɪŋ ˈɪnfənt/",
        "v2_vi": "Một thuật ngữ truyền thống trong tiếng Anh-Anh cho 'perambulator', được thiết kế để chở trẻ sơ sinh đang ngủ.",
        "v3_en": "She covered the sleeping infant in the pram with a light blanket.",
        "v3_ipa": "/ʃi ˈkʌvərd ðə ˈsliːpɪŋ ˈɪnfənt ɪn ðə præm wɪθ ə laɪt ˈblæŋkɪt/",
        "v3_vi": "Cô ấy đắp một chiếc chăn mỏng cho đứa trẻ đang ngủ trong xe nôi."
    },
    {
        "filename": "Bike.md",
        "word": "Bike",
        "pos": "Noun",
        "ipa": "/baɪk/",
        "meaning": "Xe đạp, xe gắn máy (tùy ngữ cảnh).",
        "v1_en": "A two-wheeled vehicle that you ride by pushing the pedals.",
        "v1_ipa": "/ə tuː-wiːld ˈviːɪkəl ðæt ju raɪd baɪ ˈpʊʃɪŋ ðə ˈpɛdəlz/",
        "v1_vi": "Một phương tiện hai bánh mà bạn đi bằng cách đạp bàn đạp.",
        "v2_en": "A widely used abbreviation for either a bicycle or a motorcycle.",
        "v2_ipa": "/ə ˈwaɪdli juːzd əˌbriːviˈeɪʃən fɔːr ˈiːðər ə ˈbaɪsɪkəl ɔːr ə ˈmoʊtərˌsaɪkəl/",
        "v2_vi": "Một từ viết tắt được sử dụng rộng rãi cho cả xe đạp hoặc xe máy.",
        "v3_en": "I usually ride my bike to school to get some exercise.",
        "v3_ipa": "/aɪ ˈjuːʒuəli raɪd maɪ baɪk tu skuːl tu ɡɛt sʌm ˈɛksərsaɪz/",
        "v3_vi": "Tôi thường đạp xe đến trường để tập thể dục đôi chút."
    },
    {
        "filename": "Bycicle.md",
        "word": "Bycicle (Bicycle)",
        "pos": "Noun",
        "ipa": "/ˈbaɪsɪkəl/",
        "meaning": "Xe đạp.",
        "v1_en": "A vehicle with two wheels that you move by pushing pedals with your feet.",
        "v1_ipa": "/ə ˈviːɪkəl wɪθ tuː wiːlz ðæt ju muːv baɪ ˈpʊʃɪŋ ˈpɛdəlz wɪθ jʊər fiːt/",
        "v1_vi": "Một loại xe hai bánh mà bạn di chuyển bằng cách dùng chân đẩy bàn đạp.",
        "v2_en": "A human-powered, pedal-driven vehicle with two wheels attached to a frame.",
        "v2_ipa": "/ə ˈhjuːmən-ˈpaʊərd, ˈpɛdəl-ˈdrɪvən ˈviːɪkəl wɪθ tuː wiːlz əˈtætʃt tu ə freɪm/",
        "v2_vi": "Một phương tiện chạy bằng sức người, truyền động bằng bàn đạp với hai bánh xe gắn vào khung.",
        "v3_en": "She received a shiny new bicycle for her tenth birthday.",
        "v3_ipa": "/ʃi rɪˈsiːvd ə ˈʃaɪni nuː ˈbaɪsɪkəl fɔːr hɜːr tɛnθ ˈbɜːrθdeɪ/",
        "v3_vi": "Cô bé đã nhận được một chiếc xe đạp mới sáng bóng vào sinh nhật lần thứ mười của mình."
    },
    {
        "filename": "Motorbike.md",
        "word": "Motorbike",
        "pos": "Noun",
        "ipa": "/ˈmoʊtərbaɪk/",
        "meaning": "Xe gắn máy (cách gọi thông dụng).",
        "v1_en": "A two-wheeled vehicle with an engine, like a fast, heavy bicycle.",
        "v1_ipa": "/ə tuː-wiːld ˈviːɪkəl wɪθ ən ˈɛndʒɪn, laɪk ə fæst, ˈhɛvi ˈbaɪsɪkəl/",
        "v1_vi": "Một chiếc xe hai bánh có động cơ, giống như một chiếc xe đạp nặng và chạy nhanh.",
        "v2_en": "A motorized two-wheeled vehicle, similar in construction to a motorcycle but often lighter or less powerful.",
        "v2_ipa": "/ə ˈmoʊtəraɪzd tuː-wiːld ˈviːɪkəl, ˈsɪmələr ɪn kənˈstrʌkʃən tu ə ˈmoʊtərˌsaɪkəl bʌt ˈɔːfən ˈlaɪtər ɔːr lɛs ˈpaʊərfəl/",
        "v2_vi": "Một phương tiện cơ giới hai bánh, có cấu trúc tương tự xe phân khối lớn nhưng thường nhẹ hơn hoặc ít công suất hơn.",
        "v3_en": "In Vietnam, almost every family owns at least one motorbike for daily commuting.",
        "v3_ipa": "/ɪn ˌviɛtˈnɑːm, ˈɔːlmoʊst ˈɛvri ˈfæməli oʊnz æt liːst wʌn ˈmoʊtərbaɪk fɔːr ˈdeɪli kəˈmjuːtɪŋ/",
        "v3_vi": "Ở Việt Nam, hầu như mọi gia đình đều sở hữu ít nhất một chiếc xe máy để đi lại hàng ngày."
    },
    {
        "filename": "Motorcycle.md",
        "word": "Motorcycle",
        "pos": "Noun",
        "ipa": "/ˈmoʊtərˌsaɪkəl/",
        "meaning": "Xe mô tô, xe máy.",
        "v1_en": "A large, fast vehicle with two wheels and a powerful engine.",
        "v1_ipa": "/ə lɑːrdʒ, fæst ˈviːɪkəl wɪθ tuː wiːlz ænd ə ˈpaʊərfəl ˈɛndʒɪn/",
        "v1_vi": "Một phương tiện lớn, di chuyển nhanh với hai bánh và động cơ mạnh mẽ.",
        "v2_en": "A heavy, two-wheeled motor vehicle specifically designed for high-speed travel on roads.",
        "v2_ipa": "/ə ˈhɛvi, tuː-wiːld ˈmoʊtər ˈviːɪkəl spəˈsɪfɪkli dɪˈzaɪnd fɔːr haɪ-spiːd ˈtrævəl ɑːn roʊdz/",
        "v2_vi": "Một phương tiện cơ giới hai bánh phân khối lớn được thiết kế đặc biệt để di chuyển ở tốc độ cao trên đường trường.",
        "v3_en": "He wore a black leather jacket and a helmet while riding his motorcycle.",
        "v3_ipa": "/hi wɔːr ə blæk ˈlɛðər ˈdʒækɪt ænd ə ˈhɛlmɪt waɪl ˈraɪdɪŋ hɪz ˈmoʊtərˌsaɪkəl/",
        "v3_vi": "Anh ấy mặc một chiếc áo khoác da màu đen và đội mũ bảo hiểm trong khi lái chiếc mô tô của mình."
    },
    {
        "filename": "Crane.md",
        "word": "Crane",
        "pos": "Noun",
        "ipa": "/kreɪn/",
        "meaning": "Cần cẩu.",
        "v1_en": "A very tall machine used for lifting heavy things high into the air.",
        "v1_ipa": "/ə ˈvɛri tɔːl məˈʃiːn juːzd fɔːr ˈlɪftɪŋ ˈhɛvi θɪŋz haɪ ˈɪntu ðə ɛr/",
        "v1_vi": "Một cỗ máy rất cao được dùng để nâng những vật nặng lên cao trong không trung.",
        "v2_en": "A large, tall machine used primarily in construction for hoisting and moving massive loads.",
        "v2_ipa": "/ə lɑːrdʒ, tɔːl məˈʃiːn juːzd praɪˈmɛrəli ɪn kənˈstrʌkʃən fɔːr ˈhɔɪstɪŋ ænd ˈmuːvɪŋ ˈmæsɪv loʊdz/",
        "v2_vi": "Một cỗ máy lớn, cao được sử dụng chủ yếu trong xây dựng để cẩu và di chuyển các khối lượng hàng lớn.",
        "v3_en": "The construction crew used a giant crane to place the steel beams on top of the building.",
        "v3_ipa": "/ðə kənˈstrʌkʃən kruː juːzd ə ˈdʒaɪənt kreɪn tu pleɪs ðə stiːl biːmz ɑːn tɑːp ʌv ðə ˈbɪldɪŋ/",
        "v3_vi": "Đội thi công đã sử dụng một cần cẩu khổng lồ để đặt các dầm thép lên nóc tòa nhà."
    },
    {
        "filename": "Scooter.md",
        "word": "Scooter",
        "pos": "Noun",
        "ipa": "/ˈskuːtər/",
        "meaning": "Xe tay ga, xe trượt scooter.",
        "v1_en": "A light vehicle with two wheels, either pushed with a foot or powered by a small engine.",
        "v1_ipa": "/ə laɪt ˈviːɪkəl wɪθ tuː wiːlz, ˈiːðər pʊʃt wɪθ ə fʊt ɔːr ˈpaʊərd baɪ ə smɔːl ˈɛndʒɪn/",
        "v1_vi": "Một phương tiện hạng nhẹ có hai bánh, có thể đẩy bằng chân hoặc chạy bằng động cơ nhỏ (xe tay ga).",
        "v2_en": "A lightweight motorized or human-powered two-wheeled vehicle featuring a step-through frame.",
        "v2_ipa": "/ə ˈlaɪtweɪt ˈmoʊtəraɪzd ɔːr ˈhjuːmən-ˈpaʊərd tuː-wiːld ˈviːɪkəl ˈfiːtʃərɪŋ ə stɛp-θruː freɪm/",
        "v2_vi": "Một phương tiện hai bánh nhẹ chạy bằng động cơ hoặc sức người, có thiết kế khung sàn để chân qua.",
        "v3_en": "She rides her electric scooter to the nearby grocery store every day.",
        "v3_ipa": "/ʃi raɪdz hɜːr ɪˈlɛktrɪk ˈskuːtər tu ðə ˈnɪrbaɪ ˈɡroʊsəri stɔːr ˈɛvri deɪ/",
        "v3_vi": "Cô ấy lái chiếc xe tay ga điện của mình đến cửa hàng tạp hóa gần đó mỗi ngày."
    },
    {
        "filename": "Hot Air Balloon.md",
        "word": "Hot Air Balloon",
        "pos": "Noun",
        "ipa": "/hɑːt ɛr bəˈluːn/",
        "meaning": "Khinh khí cầu.",
        "v1_en": "A huge balloon with a basket underneath that people ride in to fly.",
        "v1_ipa": "/ə hjuːdʒ bəˈluːn wɪθ ə ˈbæskɪt ˌʌndərˈniːθ ðæt ˈpiːpəl raɪd ɪn tu flaɪ/",
        "v1_vi": "Một quả bóng bay khổng lồ có giỏ bên dưới mà người ta ngồi vào để bay lên.",
        "v2_en": "A lighter-than-air aircraft consisting of a large envelope filled with heated air to achieve lift.",
        "v2_ipa": "/ə ˈlaɪtər-ðæn-ɛr ˈɛrkræft kənˈsɪstɪŋ ʌv ə lɑːrdʒ ˈɛnvəˌloʊp fɪld wɪθ ˈhiːtɪd ɛr tu əˈtʃiːv lɪft/",
        "v2_vi": "Một loại khí cụ bay nhẹ hơn không khí bao gồm một lớp vỏ lớn được chứa đầy không khí nóng để tạo lực nâng.",
        "v3_en": "Taking a ride in a hot air balloon at sunrise is an unforgettable experience.",
        "v3_ipa": "/ˈteɪkɪŋ ə raɪd ɪn ə hɑːt ɛr bəˈluːn æt ˈsʌnraɪz ɪz ən ˌʌnfərˈɡɛtəbəl ɪkˈspɪriəns/",
        "v3_vi": "Đi khinh khí cầu vào lúc bình minh là một trải nghiệm khó quên."
    },
    {
        "filename": "Trolley.md",
        "word": "Trolley",
        "pos": "Noun",
        "ipa": "/ˈtrɑːli/",
        "meaning": "Xe đẩy (siêu thị, hành lý), xe điện mặt đất.",
        "v1_en": "A cart with wheels you use to carry things in a store, or a kind of street train.",
        "v1_ipa": "/ə kɑːrt wɪθ wiːlz ju juːz tu ˈkæri θɪŋz ɪn ə stɔːr, ɔːr ə kaɪnd ʌv striːt treɪn/",
        "v1_vi": "Một chiếc xe đẩy có bánh bạn dùng để chở đồ trong cửa hàng, hoặc một loại tàu điện trên phố.",
        "v2_en": "A wheeled conveyance used for transporting goods, or a passenger vehicle running on tracks along city streets.",
        "v2_ipa": "/ə wiːld kənˈveɪəns juːzd fɔːr trænˈspɔːrtɪŋ ɡʊdz, ɔːr ə ˈpæsɪndʒər ˈviːɪkəl ˈrʌnɪŋ ɑːn træks əˈlɔːŋ ˈsɪti striːts/",
        "v2_vi": "Một phương tiện có bánh xe được sử dụng để vận chuyển hàng hóa, hoặc một phương tiện chở khách chạy trên đường ray dọc các đường phố.",
        "v3_en": "She filled the shopping trolley with fresh vegetables and fruits.",
        "v3_ipa": "/ʃi fɪld ðə ˈʃɑːpɪŋ ˈtrɑːli wɪθ frɛʃ ˈvɛdʒtəbəlz ænd fruːts/",
        "v3_vi": "Cô ấy đã chất đầy xe đẩy siêu thị với trái cây và rau củ tươi."
    },
    {
        "filename": "Cable Car.md",
        "word": "Cable Car",
        "pos": "Noun",
        "ipa": "/ˈkeɪbəl kɑːr/",
        "meaning": "Cáp treo.",
        "v1_en": "A vehicle that hangs from a thick wire and carries people up a mountain.",
        "v1_ipa": "/ə ˈviːɪkəl ðæt hæŋz frəm ə θɪk waɪr ænd ˈkæriz ˈpiːpəl ʌp ə ˈmaʊntən/",
        "v1_vi": "Một phương tiện treo lơ lửng trên một sợi dây cáp dày và chở người lên núi.",
        "v2_en": "An aerial passenger vehicle suspended from and pulled by a continuously moving cable.",
        "v2_ipa": "/ən ˈɛriəl ˈpæsɪndʒər ˈviːɪkəl səˈspɛndɪd frəm ænd pʊld baɪ ə kənˈtɪnjuəsli ˈmuːvɪŋ ˈkeɪbəl/",
        "v2_vi": "Một phương tiện chở khách trên không được treo và kéo bởi một sợi cáp chuyển động liên tục.",
        "v3_en": "We rode the cable car to the top of the mountain to get a better view.",
        "v3_ipa": "/wi roʊd ðə ˈkeɪbəl kɑːr tu ðə tɑːp ʌv ðə ˈmaʊntən tu ɡɛt ə ˈbɛtər vjuː/",
        "v3_vi": "Chúng tôi đã đi cáp treo lên đỉnh núi để có được tầm nhìn tốt hơn."
    },
    {
        "filename": "Fire Truck.md",
        "word": "Fire Truck",
        "pos": "Noun",
        "ipa": "/faɪr trʌk/",
        "meaning": "Xe cứu hỏa.",
        "v1_en": "A big red truck carrying water and firefighters to stop fires.",
        "v1_ipa": "/ə bɪɡ rɛd trʌk ˈkæriɪŋ ˈwɔːtər ænd ˈfaɪərˌfaɪtərz tu stɑːp faɪrz/",
        "v1_vi": "Một chiếc xe tải lớn màu đỏ chở nước và lính cứu hỏa đi dập tắt đám cháy.",
        "v2_en": "A specialized emergency vehicle equipped to extinguish fires and perform rescue operations.",
        "v2_ipa": "/ə ˈspɛʃəlaɪzd ɪˈmɜːrdʒənsi ˈviːɪkəl ɪˈkwɪpt tu ɪkˈstɪŋɡwɪʃ faɪrz ænd pərˈfɔːrm ˈrɛskjuː ˌɑːpəˈreɪʃənz/",
        "v2_vi": "Một phương tiện khẩn cấp chuyên dụng được trang bị để dập tắt hỏa hoạn và thực hiện các hoạt động cứu hộ.",
        "v3_en": "The fire truck arrived within minutes to put out the burning house.",
        "v3_ipa": "/ðə faɪr trʌk əˈraɪvd wɪˈðɪn ˈmɪnɪts tu pʊt aʊt ðə ˈbɜːrnɪŋ haʊs/",
        "v3_vi": "Xe cứu hỏa đã đến trong vòng vài phút để dập tắt ngôi nhà đang cháy."
    },
    {
        "filename": "Bus.md",
        "word": "Bus",
        "pos": "Noun",
        "ipa": "/bʌs/",
        "meaning": "Xe buýt.",
        "v1_en": "A large road vehicle that carries a lot of passengers along a fixed route.",
        "v1_ipa": "/ə lɑːrdʒ roʊd ˈviːɪkəl ðæt ˈkæriz ə lɑːt ʌv ˈpæsɪndʒərz əˈlɔːŋ ə fɪkst ruːt/",
        "v1_vi": "Một phương tiện giao thông đường bộ lớn chở nhiều hành khách theo một tuyến đường cố định.",
        "v2_en": "A large commercial motor vehicle intended to transport numerous passengers along established city routes.",
        "v2_ipa": "/ə lɑːrdʒ kəˈmɜːrʃəl ˈmoʊtər ˈviːɪkəl ɪnˈtɛndɪd tu trænˈspɔːrt ˈnumərəs ˈpæsɪndʒərz əˈlɔːŋ ɪˈstæblɪʃt ˈsɪti ruːts/",
        "v2_vi": "Một phương tiện cơ giới thương mại lớn nhằm mục đích vận chuyển nhiều hành khách dọc theo các tuyến đường thành phố đã được thiết lập.",
        "v3_en": "The school bus picks up children every morning at 7 AM.",
        "v3_ipa": "/ðə skuːl bʌs pɪks ʌp ˈtʃɪldrən ˈɛvri ˈmɔːrnɪŋ æt sɛvən eɪ-ɛm/",
        "v3_vi": "Xe buýt của trường đón trẻ em vào mỗi sáng lúc 7 giờ."
    },
    {
        "filename": "Sail Boat.md",
        "word": "Sail Boat",
        "pos": "Noun",
        "ipa": "/seɪl boʊt/",
        "meaning": "Thuyền buồm.",
        "v1_en": "A boat with large pieces of cloth that catches the wind to move.",
        "v1_ipa": "/ə boʊt wɪθ lɑːrdʒ ˈpiːsɪz ʌv klɔːθ ðæt ˈkætʃɪz ðə wɪnd tu muːv/",
        "v1_vi": "Một chiếc thuyền với những tấm vải lớn đón gió để di chuyển.",
        "v2_en": "A vessel propelled partly or entirely by sails navigating via wind power.",
        "v2_ipa": "/ə ˈvɛsəl prəˈpɛld ˈpɑːrtli ɔːr ɪnˈtaɪərli baɪ seɪlz ˈnævɪɡeɪtɪŋ ˈvaɪə wɪnd ˈpaʊər/",
        "v2_vi": "Một con tàu di chuyển một phần hoặc hoàn toàn bằng buồm nhờ sức gió.",
        "v3_en": "They spent the afternoon drifting across the bay in their small sail boat.",
        "v3_ipa": "/ðeɪ spɛnt ðə ˌæftərˈnuːn ˈdrɪftɪŋ əˈkrɔːs ðə beɪ ɪn ðɛr smɔːl seɪl boʊt/",
        "v3_vi": "Họ đã dành cả buổi chiều trôi dạt trên vịnh bằng chiếc thuyền buồm nhỏ của mình."
    },
    {
        "filename": "Wheel Chair.md",
        "word": "Wheel Chair",
        "pos": "Noun",
        "ipa": "/wiːl tʃɛr/",
        "meaning": "Xe lăn.",
        "v1_en": "A chair with wheels used by someone who cannot walk.",
        "v1_ipa": "/ə tʃɛr wɪθ wiːlz juːzd baɪ ˈsʌmwʌn hu kænˈnɑːt wɔːk/",
        "v1_vi": "Một chiếc ghế có bánh xe được sử dụng bởi người không thể đi lại.",
        "v2_en": "A mobility device consisting of a chair mounted on large wheels, assisting individuals with physical disabilities.",
        "v2_ipa": "/ə moʊˈbɪlɪti dɪˈvaɪs kənˈsɪstɪŋ ʌv ə tʃɛr ˈmaʊntɪd ɑːn lɑːrdʒ wiːlz, əˈsɪstɪŋ ˌɪndɪˈvɪdʒuəlz wɪθ ˈfɪzɪkəl dɪsəˈbɪlɪtiz/",
        "v2_vi": "Một thiết bị hỗ trợ di chuyển bao gồm một chiếc ghế gắn trên các bánh xe lớn, giúp những người khuyết tật về thể chất.",
        "v3_en": "The building has a ramp to make it easier for people in wheel chairs to enter.",
        "v3_ipa": "/ðə ˈbɪldɪŋ hæz ə ræmp tu meɪk ɪt ˈiːziər fɔːr ˈpiːpəl ɪn wiːl tʃɛrz tu ˈɛntər/",
        "v3_vi": "Tòa nhà có một đường dốc để những người ngồi xe lăn vào dễ dàng hơn."
    }
]

template = """# {word}
* **Từ loại:** {pos}
* **IPA:** {ipa}
* **Nghĩa tiếng Việt:** {meaning}

**1. Cách giải thích đơn giản nhất (Dành cho giao tiếp hàng ngày)**
> {v1_en}
> 
> {v1_ipa}
> 
> {v1_vi}

**2. Cách giải thích chi tiết hơn (Dùng từ vựng tốt hơn một chút)**
> {v2_en}
> 
> {v2_ipa}
> 
> {v2_vi}

**3. Đưa ra ví dụ thực tế (Cách tốt nhất để người nghe hiểu ngay)**
> {v3_en}
> 
> {v3_ipa}
> 
> {v3_vi}
"""

for v in vocab_list:
    filepath = os.path.join(output_dir, v["filename"])
    content = template.format(**v)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

print(f"Successfully generated {len(vocab_list)} markdown files in {output_dir}")
